Repository MOV-AI/frontend-npm-lib-core, pull requests merged in 2022-10, with the labels that each got.

#112 FP-2063 : Fixed UI not reflecting Robot going offline
  src/api/RobotManager/Robot.ts
  src/api/RobotManager/RobotManager.ts
  src/api/Utils/constants.js
  src/models/robot.ts
  webpack.config.js
Labels: bug, hotfix

#113 New release
  src/api/RobotManager/Robot.ts
  src/api/RobotManager/RobotManager.ts
  src/api/Utils/constants.js
  src/models/robot.ts
  webpack.config.js
Labels: bug, release-candidate, hotfix

#115 Added new utils and constants
  src/api/Utils/Utils.js
  src/api/Utils/constants.js
  src/api/index.ts
Labels: enhancement

#116 new release
  src/api/Utils/Utils.js
  src/api/Utils/constants.js
  src/api/index.ts
Labels: release-candidate
