Repository MOV-AI/frontend-npm-lib-core, pull requests merged in 2023-01, with the labels that each got.

#124 FP-2181: Added safety to parsePath function that was causing crashes
  .devcontainer/Dockerfile
  src/api/Document/Document.js
Labels: bug

#127 new release
  .devcontainer/devcontainer.json
  CHANGELOG.md
  src/api/RobotManager/Robot.ts
  src/api/RobotManager/RobotManager.ts
  test/index.html
Labels: release-candidate

#128 new release
  src/api/RobotManager/RobotManager.ts
Labels: bug, release-candidate

#129 new release
  src/api/User/User.ts
  src/api/Utils/Utils.js
  tsconfig.json
Labels: release-candidate

#131 new release
  src/api/RobotManager/Robot.ts
  src/api/RobotManager/RobotManager.ts
  src/models/robot.ts
Labels: enhancement, release-candidate

#132 new release
  src/api/RobotManager/RobotManager.ts
  test/index.html
Labels: bug, release-candidate
